repos:
  - repo: local
    hooks:
      - id: poe-check
        name: poe check
        language: system
        entry: "poe"
        args: ["check"]
        pass_filenames: false
        always_run: true