# azure-pipelines.yml

# Manual-only pipeline on Windows
trigger: none
pr: none

pool:
  vmImage: 'windows-latest'   # Microsoft-hosted Windows image

steps:
  - checkout: self
  - task: PoliCheck@2
    inputs:
      targetType: 'F'
      targetArgument: 'mcp-interviewer/src'
      
  - task: PostAnalysis@2
    inputs:
      GdnBreakAllTools: false
      GdnBreakGdnToolPoliCheck: true
      GdnBreakGdnToolPoliCheckSeverity: 'Warning'