name: Build

on:
  workflow_run:
    workflows: ["Check"]
    types:
      - completed
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13"]
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Build package
      run: |
        uv sync
        uv build
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dist-python-${{ matrix.python-version }}
        path: dist/*
        retention-days: 7
    
    - name: Check build artifacts
      run: |
        ls -la dist/
        uv pip install --system check-wheel-contents
        check-wheel-contents dist/*.whl