name: Check
permissions:
  contents: read

on:
  push:
    branches: ["**"]
    paths:
      - 'src/**'
      - 'pyproject.toml'
      - 'uv.lock'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'src/**'
      - 'pyproject.toml'
      - 'uv.lock'
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Install dependencies
        run: uv sync --group dev --all-extras

      - name: Run poe check
        run: uv run poe check
